<a href="https://colab.research.google.com/github/Manmith1321/B19_1321/blob/main/LAB_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[20,21,30,45,711]
print(l)
if 30 in l:
  print("Found")
else:
  print("Not Found")


[20, 21, 30, 45, 711]
Found


In [ ]:
l=[10,55.5,"cse"]
print(l)

[10, 55.5, 'cse']


In [ ]:
l=[20,21,30,45,711]
l.append(50)
print(l)

[20, 21, 30, 45, 711, 50]


In [ ]:
l=[20,21,30,45,711,50]
l.remove(30)
print(l)
l.insert(2,25)
print(l)
l.sort()
print(l)
l.reverse()
print(l)
print(sum(l))
print(max(l))
print(min(l))

[20, 21, 45, 711, 50]
[20, 21, 25, 45, 711, 50]
[20, 21, 25, 45, 50, 711]
[711, 50, 45, 25, 21, 20]
872
711
20


In [ ]:
student=[[10,20],[30,40],[50,60],[70,80],[90,100]]
print(student)

[[10, 20], [30, 40], [50, 60], [70, 80], [90, 100]]


In [ ]:
t=(10,20,30,40,50,60,70)
print(t)
t=(10,20,30,40,50,20)
print(t)
t=(20,98.99,"cse")
for i in t:
  print(type(i),i)
if 20 in t:
  print("found")
else:
  print("not found")

(10, 20, 30, 40, 50, 60, 70)
(10, 20, 30, 40, 50, 20)
<class 'int'> 20
<class 'float'> 98.99
<class 'str'> cse
found


In [ ]:
l=[10,20,30,40,50]
my_tuple=tuple(l)
print(my_tuple)

s=((10,20),(30,40),(40,50))
print(s)

(10, 20, 30, 40, 50)
((10, 20), (30, 40), (40, 50))


In [ ]:
t=[20,30,90,70,80]
print(t.count(30))
print(t.index(20))

1
0


In [ ]:
student={"name":"python","id":"21","branch":"cse"}
print(student)
print(student.keys())
print(student.values())
print(student.items())

for key,value in student.items():
  print(key,":",value)

#add
student["college"]="SRU"
print(student)

#update and delete
student["branch"]="AIML"
del student["id"]
print(student)

#nested dictionary
s={"101":{"name":"java","id":"21"}, "102":{"name":"python","id":"22"}}
print(s["102"]["name"])

{'name': 'python', 'id': '21', 'branch': 'cse'}
dict_keys(['name', 'id', 'branch'])
dict_values(['python', '21', 'cse'])
dict_items([('name', 'python'), ('id', '21'), ('branch', 'cse')])
name : python
id : 21
branch : cse
{'name': 'python', 'id': '21', 'branch': 'cse', 'college': 'SRU'}
{'name': 'python', 'branch': 'AIML', 'college': 'SRU'}
python


In [ ]:
print("10\t20\n30\t40\n50\t60")

10	20
30	40
50	60


In [ ]:
l=[[10,20],[30,40],[50,60]]
for i in l:
  print(*i) # * is a unpacking operator

10 20
30 40
50 60


In [ ]:
l=[[10,20],[30,40],[50,60]]
for i in l:
  print(i)

[10, 20]
[30, 40]
[50, 60]


In [ ]:
#SETS

a={1,2,3,4}
b={3,4,5,6}
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))
print("union",a|b)
print("intersection",a&b)
print("difference",a-b)
print("difference",b-a)
print(a.symmetric_difference(b))
print(a^b)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}
union {1, 2, 3, 4, 5, 6}
intersection {3, 4}
difference {1, 2}
difference {5, 6}
{1, 2, 5, 6}
{1, 2, 5, 6}


In [ ]:
s={1,2,3,4}
print(s)
s.add(5)
print(s)
s.remove(4)
print(s)
s.clear()
print(s)

{1, 2, 3, 4}
{1, 2, 3, 4, 5}
{1, 2, 3, 5}
set()


In [1]:
import numpy as np
marks = np.array([[85, 78, 92], [70, 65, 80],  [90, 88, 94],  [60, 75, 70],  [95, 85, 99] ])
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)
print(avg_marks)
print(min_marks)
print(max_marks)

print("Marks of Student 3:", marks[2])
print("Marks of Students 2 to 4: ", marks[1:4])

excellent= marks >80
print(excellent)

each_subject = marks.T
print("EACH SUBJECT MARKS", each_subject)


81.73333333333333
60
99
Marks of Student 3: [90 88 94]
Marks of Students 2 to 4:  [[70 65 80]
 [90 88 94]
 [60 75 70]]
[[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]
EACH SUBJECT MARKS [[85 70 90 60 95]
 [78 65 88 75 85]
 [92 80 94 70 99]]
