<a href="https://colab.research.google.com/github/Manmith1321/B19_1321/blob/main/LAB_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# 3. Writing to a file
# Open file in write mode
fp = open("example.txt","w")

#Write text to file
fp.write("Hello,B.tech students!\n")
fp.write("this os file handling in python.\n")
fp.write("sr university.\n")
fp.write("manmith vardhan.\n")

#Close the file
fp.close()
print("data written successfully")

data written successfully


In [9]:
# 4. Readimg from a line
fp = open("example.txt","r")
content=fp.read()
print("file content:\n",content)
fp.close()
fp.close()

file content:
 Hello,B.tech students!
this os file handling in python.
sr university.
manmith vardhan.



In [13]:
# 5. reading line by line
fp=open("example.txt","r")
line1=fp.readline()
print("First line",line1)
line2=fp.readline()
print("Second line",line2)
line3=fp.readline()
print("Third line",line3)
line4=fp.readline()
print("Fourth line",line4)
fp.close()

First line Hello,B.tech students!

Second line this os file handling in python.

Third line sr university.

Fourth line manmith vardhan.



In [16]:
# 6. Reading all lines into a list
file = open("example.txt","r")
lines = file.readlines()

print("all lines at list:\n", lines)
file.close()

all lines at list:
 ['Hello,B.tech students!\n', 'this os file handling in python.\n', 'sr university.\n', 'manmith vardhan.\n']


In [19]:
# 7. Appending data to on existing file
file = open("example.txt","a")
file.write("third year\n")
file.close()

In [21]:
# 8. Using eith statement (Best practice)
# the with statement automatically closes the file
with open("example.txt","r") as fp:
    data = fp.read()
    print(data)

Hello,B.tech students!
this os file handling in python.
sr university.
manmith vardhan.
third year
third year
third year



In [28]:
# 9. Working with CSV files
# writing to csv
with open("data.csv","w",newline = '') as fp:
  wr = csv.writer(fp)
  wr.writerows([["Name","Age","Course"],["Manmith",19,"CSE"],["Dinesh",20,"EEE"]])

#READING TO CSV FILES
with open("data.csv","r") as file:
  re = csv.reader(file)
  for row in re:
    print(row)

['Name', 'Age', 'Course']
['Manmith', '19', 'CSE']
['Dinesh', '20', 'EEE']


In [40]:
#NUMPY ARRAYS
#1D Array
import numpy as np
arr1 = np.array([1,2,3,4,5])
#print(arr1)
print("1D Array:", arr1)

#2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2) #print(arr2)

#Zeros Array
zeros_arr = np.zeros((3,3))
print("Zeros Array:\n", zeros_arr)

#Ones Array
ones_arr = np.ones((3,4))
print("Ones Array:\n", ones_arr)

#Range of numbers
range_arr = np.arange(1,10,2) #start,stop,step
print("Range Array:\n", range_arr)

#Random Array
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array:
 [1 3 5 7 9]
Random Array:
 [[0.00095992 0.46747069 0.53284026]
 [0.61071528 0.30123676 0.46856041]]


In [43]:
#ARRAY ATTRIBUTES
arr = np.array([[1,2,3],[4,5,6]])

print("Shape:", arr.shape) #(rows, columns)
print("Dimensions:", arr.ndim) #2D array
print("Data Type:", arr.dtype) #int64 or float64
print("Size:", arr.size) #total elements
print("Item size:", arr.itemsize) #Bytes per element

Shape: (2, 3)
Dimensions: 2
Data Type: int64
Size: 6
Item size: 8


In [48]:
# ARRAY OPERATIONS
# Arithmetic opertaions

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Exponent:", a**b)

# Mathematical Functions
arr = np.array([0,np.pi/2,np.pi])
print("Sin:", np.sin(arr))
print("Cos:", np.cos(arr))
print("Tan:", np.tan(arr))
print("Exp:", np.exp(arr))
print("Sqrt:", np.sqrt(arr))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponent: [  1  32 729]
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exp: [ 1.          4.81047738 23.14069263]
Sqrt: [0.         1.25331414 1.77245385]


In [47]:
# AGGREGATE FUNCTIONS
arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Sum along axis 0:", np.sum(arr, axis=0)) #column wise sum
print("Sum along axis 1:", np.sum(arr, axis=1)) #row wise sum

Sum: 21
Min: 1
Max: 6
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [51]:
#Matrix Operations
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n",np.dot(A,B))
print("Matrix Transpose:\n",A.T)
print("Matrix Inverse:\n",np.linalg.inv(A))
print("Matrix Determinant:\n",np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Determinant:
 -2.0000000000000004


In [52]:
#Sample Program - Student Analsis
import numpy as np
# Marks of students in 3 subjects
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
